name: Deploy latest editor
on:
  push:
    branches:
      - master
jobs:

  test:
    runs-on: ubuntu-latest

    permissions:
        contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install project dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  build:
    name: Build
    runs-on: ubuntu-latest
    depends-on: test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd
          ./update-editor.sh